# Generated by Django 5.2.15 on 2026-07-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', '貸出可能'), ('pending', '申請中'), ('borrowed', '貸出中'), ('broken', '故障中')], default='available', max_length=20, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', '申請中'), ('borrowed', '貸出中'), ('returned', '返却済み')], default='pending', max_length=20, verbose_name='貸出状態'),
        ),
    ]
